CREATE TABLE ADDRESS_UPDATES (
  CLIENT_ID varchar(50) NOT NULL,
  REQUEST_ID varchar(50),
  ADDRESS_ID INT NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE PROCEDURE AUDIT_ADDRESS_UPDATE_STORED_PROCEDURE (
  CLIENT_ID varchar(50),
  REQUEST_ID varchar(50),
  ADDRESS_ID INT
)
PARAMETER STYLE JAVA
LANGUAGE JAVA
MODIFIES SQL DATA
DYNAMIC RESULT SETS 0
EXTERNAL NAME 'org.apache.cmueller.camel.sus.cidu.part2.AuditAddressUpdateStoredProcedureDef.audit';